import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import { ContextProvider } from '@/other/Context'

export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Synk</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=0.8" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ContextProvider>
      <Navbar />
      <div className="scrollwrapper">
        <Component {...pageProps} />
      </div>
    </ContextProvider>
  </>
}
